ARMmbed/htrun

- mbed_host_tests/__init__.py
As a developer
I want to reset mbed-enabled device from command line and see serial port output
on my console
So that I can quickly verify if my device is flashed with proper software
Note: Serial port dump will stop after "{end}' terminator is found
Users can:
* Send standard serial port BREAK (-b switch) and reset device:
```
$ mbedhtrun -p COM144 -b
```
* Specify other reset plugin:
```
$ mbedhtrun -p COM144 -b -r stlink
```
* Specify baudrate and timeout for serial port:
```
$ mbedhtrun -p COM144:115200 -b
$ mbedhtrun -p COM144:115200:1 -b
```
* Use verbose mode to get more output (-v switch)
```
$ mbedhtrun -p COM144 -b -v
```
> Add 'send break functionality' with -b command line switch

- mbed_host_tests/host_tests_runner/mbed_base.py
> Refactor how reset methods get called and add a new reset method parameter

- mbed_host_tests/host_tests/base_host_test.py
> rampUp, not rumpUp.

- test/basic_ht.py
Add few simple (minor) unit tests regarding capabilities API.
> Basic unit test polishing

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_registry/host_registry.py
- test/host_registry.py
- test/host_test_base.py
> [issue 48] Rename rampUp/Down to setup/teardown

- README.md
Few tips for those who write host tests.
> Documentation updates for "how to write host tests"

- mbed_host_tests/__init__.py
> Add missing setup/teardown call

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
related issue: http://jira.arm.com/browse/IOTSFW-2144
related PR: https://github.com/ARMmbed/greentea/pull/88
> Fix hanging execution of greentea/htrun

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
related issue: https://github.com/ARMmbed/greentea/issues/90
> Prevent Queue.qsize() from raising Error on Mac OS X

- mbed_host_tests/host_tests_runner/host_test_default.py
fix issue https://github.com/ARMmbed/greentea/issues/100
related PR: https://github.com/ARMmbed/greentea/pull/102
> Catch ctrl+c and propagate to greentea

- README.md
This is response to https://github.com/ARMmbed/htrun/issues/70.
> Update README notes (port Async model changes)

- mbed_host_tests/host_tests/echo.py
Response for https://github.com/ARMmbed/htrun/issues/79.
> [ready to merge] Echo host test reply counter checks

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Fixes #96 
I suspect there may be a better way to solve this, but this works as a temporary solution.
> Workaround for serial delays by never blocking on the dut_event_queue

- README.md
Changes:
* Update README with latest changes / updated to APIs and command line.
> Add basic Quickstart and command line usage

- mbed_host_tests/host_tests_conn_process/conn_process.py
- mbed_host_tests/host_tests_conn_process/default_conn_process.py
- mbed_host_tests/host_tests_event_loop/base_event_loop.py
- mbed_host_tests/host_tests_event_loop/default_event_loop.py
- mbed_host_tests/host_tests_event_loop/event_loop.py
- mbed_host_tests/host_tests_parser/base_parser.py
- mbed_host_tests/host_tests_parser/default_parser.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- test/conn_process_factory.py
- test/event_loop_base.py
- test/event_loop_factory.py
* Moved the creation of conn process into event loop
* Fixed issue when a reset was needed the function to generate the conn process had been removed
* Removed some unneeded parameters and imports
> Fixed issue with resetting Conn Process

- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/module_copy_pyocd.py
- mbed_host_tests/host_tests_plugins/module_reset_pyocd.py
- setup.py
Add copy and reset support using pyOCD.
> Add support for pyOCD

- mbed_host_tests/host_tests_conn_proxy/conn_primitive.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_plugins/host_test_plugins.py
Fixes https://github.com/ARMmbed/htrun/issues/148
> Exit on failure to find serial port after reset

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
just cleanup a bit remote dut initialization phase
> cleanup remote dut initialization

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
check that remote resource exists before using it
> verify selected remote resource before using it

- mbed_host_tests/host_tests_plugins/module_copy_shell.py
Should avoid dropping copy failures
> And result with sync results

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
Code change picked upfrom 'Brain Daniels' repo: copy_and_remount_refactor
@studavekar @mazimkhan @bridadan : Please review
> Re-try flashing in case of flash failures.

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_plugins/module_copy_mbed.py
- mbed_host_tests/host_tests_plugins/module_copy_shell.py
Currently the method check_mount_point_ready return false even if the mount point is ready.
**READY**
- Have tests locally with mbed test and standlone mbedhtrun
@bridadan
> Fixed the return value of check_mount_point_ready

- .gitignore
Git ignore PyCharm IDE folder .idea/
> Git ignore IDE files

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
Possible fix for https://github.com/ARMmbed/htrun/issues/170
> disable disconnect right after allocation.

- setup.py
* Allow a host test to reset the device under test
* Fix a copy error on Linux
* Fix testing with RAAS
> Release Version 1.3.0

- setup.py
* Remove calls to deprecated list_mbeds_ext functions
* Keep the same extension of the executable files copied to MPS2
> Release Version 1.3.1

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- setup.py
Small fixes to allow htrun to run with Python 3.
> Fixes string issues with running in Py3

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- test/conn_primitive_remote.py
* current htrun master does not work with the new raas-pyclient versions (raises errors even though flashing/reset succeeds).
* fix __remote_flashing & __remote_reset.
> Update remote connection

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Due to lack of pull-up on different parts, the re-initialization of uart causes it to send an invalid character which we are not able to handle properly on htrun side. While partners are investigating the issue and fix, we will add this change in to handle the exception gracefully, as this bug is blocking the addition of multiple parts to our CI
> add try/exception to handle UnicodeDecodeError

- setup.py
* Add try/exception to handle UnicodeDecodeError
* Correct import statement in decorator example
> Release Version 1.4.1

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_plugins/host_test_registry.py
This is following ARMmbed/greentea#277 discussion
> Use PrettyTable with GitHub policy

- setup.py
fix for issue https://github.com/ARMmbed/htrun/issues/222
> fix pyOCD version to v0.12.0

- setup.py
**** Use PrettyTable with GitHub policy
* Document polling-timeout setting for testing apps
* Update htrun fastmodel connector to match with newer fm_agent
* fix pyOCD version to v0.12.0
> Release version 1.4.2

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_registry/host_registry.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- test/basic_ht.py
> WIP: make `--list` conistant with running WRT `-e`

- setup.py
* Add support for dynamic timeout set/adjust from DUT
* Remove references to yotta in README.md
* Update pyocd support to version 0.14.0 or later
* Make --list consistant with running WRT -e
> Release version 1.4.3

- setup.py
* Fix reference to board.getTargetType in pyocd copy plugin
> Release version 1.4.4
