ARMmbed/htrun

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- test/host_test_plugins.py
Add generic Linux flavor for OS detection function.
It will allow OS detection unit tests to smoothly pass on CircleCI machines.
> Add LinuxGeneric value to OS detection function

- mbed_host_tests/host_tests/test_socket_server_udp.py
Fix for issue https://github.com/ARMmbed/htrun/issues/28.
Host tests are loaded as objects when module is loaded. To avoid e.g. like in this case UDP server module initialization server setup was moved to separate function.
> [host test] Move UDP server init from ctor to separate function

- README.md
- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/host_test_registry.py
This PR is introducing simple Python APIs for flashing and reset. It was originally intended to be used in BLE test framework so branch name is a bit confusing.
This APIs allow test tools developers and others to develop reuse and extend flashing and reset functionality.
Functions added:
```get_host_test_list()``` - Returns list of host test names and its classes
```get_plugin_caps()``` - Returns plugins capabilities
```flash_dev()``` - Flash device with image
```reset_dev()``` - reset device
Example usage:
```
$ python
>>> import mbed_host_tests
>>> import json
>>> print json.dumps(mbed_host_tests.get_plugin_caps(), indent=4)
{
"ResetMethod": [
"default",
"eACommander",
"eACommander-usb",
"stlink"
],
"CopyMethod": [
"copy",
"cp",
"default",
"eACommander",
"eACommander-usb",
"shell", …
```
> Extra Python APIs to support Python derived test tools

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/base_host_test.py
This feature allows ```mbedhtrun``` to load and register additional host test scripts from given directory.
In many cases users will add host tests to their yotta modules preferably under ```/test/host_tests/```module directory.
Host tests script files are enumerated and registered so they can be used with local module test cases.
Not all host tests can be stored with ```mbedhtrun``` package. Some of them may and will be only used locally, for prototyping. Some host tests may just be very module dependent and should not be stored with ``mbedhtrun```. 
New CLI switch ```-e``` / ```--enum-host-tests``` defines (yotta module) directory in which we will store local host tests. You can also point ```mbedhtrun``` to different directory with pool of host tests.
**Note**: Directory …
```
> Dynamic host test loader (from directory location)

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_plugins/host_test_registry.py
- mbed_host_tests/host_tests_plugins/module_copy_jn51xx.py
- mbed_host_tests/host_tests_plugins/module_copy_stlink.py
- mbed_host_tests/host_tests_plugins/module_reset_jn51xx.py
- mbed_host_tests/host_tests_plugins/module_reset_stlink.py
- mbed_host_tests/host_tests_runner/mbed_base.py
Changes:
* Add API to determine if host test plugin works under OS
* Add default value for OS name in OS compatibility plugin APIs
* Add OS support flag to --plugins switch
* Add jn51xx plugins to plugin pool
* Add new format of serial port:
* Use PORT:SPEED or PORT:SPEED:TIMEOUT to define more specific characteristics of serial port
Example 1: ```-p COM4:115200```
Example 2: ```COM4:115200:0.5 where 0.5 is a serial port default timeout```
> Updates to plugin system and serial port configuration options

- mbed_host_tests/host_tests_plugins/module_reset_mbed.py
- test/host_registry.py
- test/host_test_plugins.py
Below API is deprecated for pyserial 3.x versions!
* http://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.Serial.sendBreak
* http://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.Serial.setBreak
See:
* http://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.Serial.send_break
* http://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.Serial.break_condition
Note: **For send break to work** we need to make sure your DAPlink (Interface firmware) **version is >= 0226**.
> Support for pyserial 3.0

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_runner/mbed_base.py
* Small change in host print regarding port/disk settings and PID:
```
$ mbedhtrun
mbedhtrun
HOST: Instrumentation: "None" and disk: "None"
HOST: My PID is 10332
...
```
**Note**: It should be easier to kill this process in the future knowing its PID from the beginning.
* Fixed not handled serial port parameter parsing:
```
$ mbedhtrun
Traceback (most recent call last):
File "C:\Python27\Scripts\mbedhtrun-script.py", line 9, in <module>
load_entry_point('mbed-host-tests', 'console_scripts', 'mbedhtrun')()
File "c:\work\pypi\htrun\mbed_host_tests\mbedhtrun.py", line 29, in main
test_selector = DefaultTestSelector(init_host_test_cli_params())
File "c:\work\pypi\htrun\mbed_host_tests\__init__.py", line 254, in __init__
DefaultTestSelectorBase.__init__(self, options)
File …
```
> Add PID print

- README.md
Pull request for fixing issue #51 
README.md updated with description on how host test classes are enumerated and what happens if a host test file fails to load.
> Added description about the enumeration of host test scripts.

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/mbedhtrun.py
Fix for issue https://github.com/ARMmbed/greentea/issues/48
Changes:
- Added a stdin monitoring thread
- Aborting selector when stdin is closed.
- Check for abort at different steps of execution.
- Selector aborts test case.
- Added new based class method abort().
Creating PR for feedback from issue creator. Unit tests will be added soon.
This PR is complimentary to https://github.com/ARMmbed/greentea/pull/63 (they should come at the same time in release.
> Aborting mechanism when parent process wants to stop mbedhtrun

- mbed_host_tests/host_tests/default_auto.py
- mbed_host_tests/host_tests_plugins/module_reset_mbed.py
- test/host_test_os_detect.py
- test/host_test_plugins.py
Fix for https://github.com/ARMmbed/htrun/issues/56.
We falsely assumed pySerial will have 3.x version numbers. So it was parsed to float, now with 3.0.1 version we got into trouble.
This PR tries to fix that...
> Add better detection of pySerial 3.x.y libraries

- README.md
- mbed_host_tests/mbedflsh.py
- setup.py
Simple command ```mbedflsh``` added to help flashing devices from command line without extra hassle caused by one trillion of switches in ```mbedhtrun```.
```
$ mbedflsh -h
Usage: mbedflsh-script.py [options]
Flash mbed devices from command line.This module is using build in to mbed-
host-tests plugins used for flashing mbed devices
Options:
-h, --help            show this help message and exit
-f FILENAME, --file=FILENAME
File to flash onto mbed device
-d DISK_PATH, --disk=DISK_PATH
Target disk (mount point) path. Example: F:, /mnt/MBED
-c COPY_METHOD, --copy=COPY_METHOD
Copy (flash the target) method selector. Plugin
support: copy, cp, default, eACommander, eACommander-
usb, shell, shutil, stlink, xcopy
--plugins             Prints registered plugins and exits
--version …
```
> Add new CLI 'mbedflsh' to facilitate only mbed devices' flashing

- README.md
This document was missing required TOC section for ```README.md```.
Generated with [gittoc](https://github.com/PrzemekWirkus/git-toc)
> Add Table Of Content to README

- mbed_host_tests/host_tests/base_host_test.py
- test/event_callback_decorator.py
This is an alternative approach to implementing ```setup``` method and calling ```self.register_callback``` for registering event callbacks. 
Now event callbacks can be decorated with a decorator as ```@event_cb('<key>')```. A base implementation of ```setup``` is added in the ```BaseHostTest``` to look for decorated methods and register them as callbacks. Thus host test developers do not need to implement ```setup``` anymore. 
```
Example:
@event_callback('<event key>')
def event_handler(self, key, value, timestamp):
do something..
```
> Event handler decorator for automatic registering of event callbacks

- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests/default_auto.py
For most cases event 'end' callback has following handling:
```python
def end_event_callback(self, key, value, timestamp):
self.notify_complete(value == 'success')
```
Hence this PR implements a default callback with above handling in base ```class HostTestCallbackBase```.
Users can still over write this handler by creating a handler and registering for key 'end'. Example:
```python
def my_end_callback(self, key, value, timestamp):
....
```
> Default handling for 'end' event

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/__init__.py
base class ```BaseHostTest``` can be exported from mbed_host_tests module. Now ```event_callback``` decorator can also be imported with ```BaseHostTest```
> exporting event_callback up to be imported from mbed_host_tests

- mbed_host_tests/host_tests_runner/host_test_default.py
* Add new event ```__version``` to send ```greentea-client``` version to host from DUT.
* Handled in preamble.
```
[1457397994.44][HTST][INF] DUT greentea-client version: 0.1.7
[1457397994.44][CONN][RXD] {{__version;0.1.7}}
```
```
[1457397984.11][HTST][INF] copy image onto target...
Liczba skopiowanych plików:         1.
[1457397992.67][HTST][INF] starting host test process...
[1457397993.03][CONN][INF] starting connection process...
[1457397993.03][CONN][INF] initializing serial port listener...
[1457397993.03][SERI][INF] serial(port=COM10, baudrate=9600)
[1457397993.03][SERI][INF] reset device using 'default' plugin...
[1457397993.28][SERI][INF] wait for it...
[1457397994.28][CONN][INF] sending preamble 'e5743557-e3a5-484e-97da-b83c3f8bfb67'...
[1457397994.28][SERI][TXD] …
```
> Add greentea-client version in preamble detection

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
- Support to reset DUT in test.
- Now greentea will provide mbed platform's unique target id to confirm same device is used after reset.
Please see following sequence diagram that illustrates how a test can manage its state before a after restart:
```
DUT                     host
---                     ----
|    {{__sync;UUID}}     |
|<-----------------------|
|                        |
|    {{__sync;UUID}}     |
|----------------------->|
- - - - - - - - - - -  - -
HANDSHAKE !
- - - - - - - - - - -  - -
|                        |
|   {{__timeout;%s}}     |
|----------------------->|
|                        |
|{{__host_test_name;%s}} |
|----------------------->|
- - - - - - - - - - -  - -
TEST SUITE CONTROL UNDER 
HOST TEST 
- - - - - - - - - - -  - -     
ht = …
```
> Changes to support DUT reset in a test

- mbed_host_tests/mbedhtrun.py
Add support for when a program which uses multiprocessing has been frozen to produce a Windows executable.
See here: https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support
This may cause some RuntimeErrors like:
```
self._popen = Popen(self)
File "c:\Python27.11\lib\multiprocessing\process.py", line 130, in start
File "c:\Python27.11\lib\multiprocessing\forking.py", line 258, in __init__
self._popen = Popen(self)
File "c:\Python27.11\lib\multiprocessing\forking.py", line 258, in __init__
cmd = get_command_line() + [rhandle]
File "c:\Python27.11\lib\multiprocessing\forking.py", line 358, in get_command_line
cmd = get_command_line() + [rhandle]
File "c:\Python27.11\lib\multiprocessing\forking.py", line 358, in get_command_line
is not going to be frozen to …
```
> Add support for when a program which uses multiprocessing has been frozen

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_plugins/module_copy_mbed.py
- mbed_host_tests/host_tests_plugins/module_copy_shell.py
- mbed_host_tests/host_tests_runner/host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
- setup.py
We are not protecting test run from device mount point change when calling `mbedhtrun`.
* Add to `shell` and `shutil` plugins mount guards checking if mount point changed and/or is valid.
* If mount point changed warning will be issues and new mount point will be used for copy/flash procedure. 
* Add `htrun` version print (first print by `htrun`) for debugging purposes:
```
[1462545824.12][HTST][INF] host test executor ver. 0.2.6
```
@mazimkhan @adbridge @bridadan Please review. 
This will be delivered separately to features:
* Serial port check before reset and
* HW reset recovery feature I think.
I've called `mbedhtrun` with correct `target_id` and wrong mount point `X:` and got correct response from `HostTestPluginCopyMethod_Shell` plugin with correct mount point value of mount point …
> Add mount point checks with mbed_lstools before flashing

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_toolbox/host_functional.py
We are not protecting test run from device serial port change when calling `mbedhtrun`.
* Add to `mbed_reset` plugins guards checking if serial port changed and/or is valid.
* If serial port changed warning will be issues and new serial port will be used for reset/sendBreak procedure.
@mazimkhan @adbridge @bridadan Please review. 
This will be delivered separately to features:
* Mount point check before reset and
* HW reset recovery feature I think.
I've called `mbedhtrun` with correct `target_id` and wrong serial port `COMx:` and got correct response from `HostTestPluginBase::BasePlugin` plugin with correct serial port name from `mbed_lstools`.
Note: Connection listener will open serial port and keep it open while later reset plugin will reuse OBJECT not PORT name so we only check port …
> Add serial port checks with mbed_lstools before opening port by listener

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
Changes:
* This patch makes sure we are not taking 'unknown' device property while pooling for it.
* Improvements for two previous PRs. See https://github.com/ARMmbed/htrun/pull/85 and https://github.com/ARMmbed/htrun/pull/86.
> mbed-ls can return data for target id with wields like mount_point or serial_port set to None

- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/module_power_cycle_mbed.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
- setup.py
Extension on PR https://github.com/ARMmbed/htrun/pull/75 for hardware reset. Please see feature documentation in https://github.com/ARMmbed/htrun/pull/75
Changes:
Now ```reset_dut(reset_type)``` accepts an argument ```reset_type``` that can have two string value ```software_reset``` or ```hardware_reset```. 
* ```software_reset``` resets the device by sending break command over serial.
* ```hardware_reset``` uses mbed-tas-rm service to reset the device.
Target test can initiate software or hardware reset by sending ```software_reset``` or ```hardware_reset``` as value with a corresponding event key. Target can either send a host test handled key for which host test calls ```reset_dut```. Or target can directly send ```{{__reset_dut;<reset type>}}``` and htrun event loop will reset the …
> Hardware reset feature

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
This change will show all loadable from current directory host tests.
Normally users use ```--list``` switch to show all loadable host tests:
```
$ cd <module>
```
```
$ mbedhtrun --list
```
```
'default'       : <class 'mbed_host_tests.host_tests.default_auto.DefaultAuto'>()
'default_auto'  : <class 'mbed_host_tests.host_tests.default_auto.DefaultAuto'>()
'detect_auto'   : <class 'mbed_host_tests.host_tests.detect_auto.DetectPlatformTest'>()
'dev_null_auto' : <class 'mbed_host_tests.host_tests.dev_null_auto.DevNullTest'>()
'echo'          : <class 'mbed_host_tests.host_tests.echo.EchoTest'>()
'hello_auto'    : <class 'mbed_host_tests.host_tests.hello_auto.HelloTest'>()
'rtc_auto'      : <class 'mbed_host_tests.host_tests.rtc_auto.RTCTest'>()
'wait_us_auto'  : <class …
```
> [ready to merge] Add to --list switch a -e ./test/host_tests

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
Note: there might be up to 3 minutes delay in mount on some OSs.
Changes:
* Change pooling for serial port to 1 minute (it will be a sec longeer because mbed-ls calls take extra few ms)
* Add simple "start pooling for serial" print for debuging.
Note: there can be following this one PR with actual pooling time switch command in mbedhtrun.
This PR tries to address https://github.com/ARMmbed/htrun/issues/89.
> Add serial port mount time delay to 1 minute

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_plugins/module_copy_mbed.py
- mbed_host_tests/host_tests_plugins/module_copy_shell.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
This is patch for:
* Add serial port mount time discovery (with mbed-ls) delay to 1 minute, see #90.
* Serial port mbed-ls guard failed, see #89
* I've noticed wrong behavior with two previous PRs about serial port. When increasing pooling to >10 secs we will create timeout on event loop itself (its default timeout is 10 secs - wait for `__sync` and `__timeout` message from device).
Note:
* This PR will not allow us to remove switch `-C <sec>` which sets `program_cycle_s` - delay in seconds after we flash device. I've checked and removing it with this PR will cause errors such as "disk not ready" under Windows 7. 
* Add default 60 sec timeout for event queue when we wait for serial port in conn_process.
* This will expand event queue lifetime so it can wait for serial port pooling and …
> Patch: serial port pooling time improvements (see #90)

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Changes:
* Change `timeout` parameter for queue `dut_event_queue` to `1`.
* Tested with RPI2, Ubuntu 14 LTS and Windows 7. Packages tested: sal-test, mbed-drivers.
* This issue was 100% reproducible for RPI2 setup.
* Issue found with bisect in `htrun` v0.2.9.
@mazimkhan Azim, please check and let me know if I can merge and release.
@bridadan FYI.
> Bug-fix: event queue hangs under RPI2

- mbed_host_tests/host_tests/wait_us_auto.py
Changes:
* Now if there are no ticks we will return False by default
In below example we will execute faulty ticker test where no ticks are outputed.
Host test (in case of no ticks) should return False.
```
[1464859336.01][SERI][TXD] {{__sync;1cb1979c-e353-4d3a-9d49-b20e68428174}}
[1464859337.02][CONN][RXD] {{__sync;1cb1979c-e353-4d3a-9d49-b20e68428174}}
[1464859337.02][CONN][RXD] {{__version;1.1.0}}
[1464859337.02][CONN][RXD] {{__timeout;20}}
[1464859337.02][CONN][RXD] {{__host_test_name;wait_us_auto}}
[1464859337.02][CONN][INF] found SYNC in stream: {{__sync;1cb1979c-e353-4d3a-9d49-b20e68428174}}, queued...
[1464859337.02][CONN][INF] found KV pair in stream: {{__version;1.1.0}}, queued...
[1464859337.02][CONN][INF] found KV pair in stream: {{__timeout;20}}, queued... …
```
> Bug-fix: If no ticks recorded host test returns True

- mbed_host_tests/__init__.py
Example after change:
```
$ mbedhtrun --list
```
```
+-----------------------------+---------------------------------------------------------------------+------------------------------------------------------------------+
| name                        | class                                                               | origin                                                           |
+-----------------------------+---------------------------------------------------------------------+------------------------------------------------------------------+
| default                     | <class 'mbed_host_tests.host_tests.default_auto.DefaultAuto'>       | mbed-host-tests                                                  |
| default_auto                | <class …
```
> Add table while printing to --list switch

- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
This PR is response for https://github.com/ARMmbed/htrun/issues/80.
Changes:
* Add check if custom host test (in most cases loaded from ```<module>/test/host_tests```) inherits from ```mbed_host_tests.BaseHostTest()``` and calls required ```BaseHostTest.__init__(self)``` ctor.
This change applies to all developers writing host tests where they create custom ctor for their host test.
Example:
```python
from mbed_host_tests import BaseHostTest
class MyCustomHostTest(BaseHostTest):
def __init__(self):
BaseHostTest.__init__(self)    # OK
pass
```
or
```python
from mbed_host_tests import BaseHostTest
class MyCustomHostTest(BaseHostTest):
```
In case users have custom host test with ```__init__(self) defined and no call to ```BaseHostTest.__init__(self)``` ```htrun``` will yield error and …
```
> Add warning regarding missing BaseHostTest ctor call in custom host test

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Changes:
* Switch `-R` was not supported in new event loop `CONN` process.
> Add back support for -R <timeout-after-reset> command line switch

- mbed_host_tests/__init__.py
When PR #98 was merged (867e83072651c756649c8ef4a926a2700b191b3b), the default value of 1 second for `forced_reset_timeout` was incorrectly removed. Instead it was being set to `None`, which caused targets to not sync correctly.
This PR adds the default of 1 second back to the `forced_reset_timeout` option.
```
mbedgt: selecting test case observer...
calling mbedhtrun: mbedhtrun -d D: -p COM249:9600 -f "C:\m\test\.build\tests\RZ_A1H\GCC_ARM\mbed-os\TESTS\mbed_drivers\rtc\mbed-os-tests-mbed_
drivers-rtc.bin" -C 2 -c shell -m RZ_A1H -t 550002210FB3423630F7860B
mbedgt: mbed-host-test-runner: started
[1465986552.61][HTST][INF] host test executor ver. 0.2.15
[1465986552.61][HTST][INF] copy image onto target...
1 file(s) copied.
Plugin info: HostTestPluginCopyMethod_Shell::CopyMethod: Waiting …
```
> Re-adds the default reset timeout of 1 second

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Sync packet management allows us to manipulate the way `htrun` sends `__sync` packet(s).
With current settings we can force on `htrun` to send `__sync` packets in this manner:
```
* --sync=0        - No sync packets will be sent to target platform
```
```
* --sync=-1       - __sync packets will be sent unless we will reach
timeout or proper response is sent from target platform
```
``` 
* --sync=N        - Send up to N __sync packets to target platform. Response
is sent unless we get response from target platform or
timeout occur
```
```
mbedhtrun ... --sync=3 ... --skip-flashing
```
```
[1466093139.60][HTST][INF] host test executor ver. 0.2.17
[1466093139.60][HTST][INF] copy image onto target... SKIPPED!
[1466093139.61][HTST][INF] starting host test process...
[1466093140.26][CONN][INF] …
```
> Add new switch --sync to manipulate how many times htrun should send __sync to target platform

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
This is a preparation to have a exchangeable `CONN` process. In the future we want to replace default `SerialConnectorPrimitive` with objects which implement `ConectionPrimitive` interface.
We want to be able to load 3rd party / external CONNectors in the future. In most cases those would be GRM (Global Resource Managers) which can allocate resource and create resource handlers.
GRM resources should behave similar to Serial port primitive:
* Provide CRUD like API
* Provide reset / flash features
* Enumerate resources `mbed-ls` style
> Add ConectionPrimitive as base class for SerialConnectorPrimitive

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy_logger.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Adaption of the 'HtrunLogger' class to replace the custom outputting to stdout, with the builtin 'logging' module in Python. Now all of the logging will go through the 'logging' module, and will be formatted in the same way as before. Further iterations will fully remove the class, and rely solely on calling the logging code. The issue for this enhancement is #102.
@adbridge 
@mazimkhan 
@PrzemekWirkus
> Converted HtrunLogger to use Python 'logging' module removing custom lock

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
This is in response to the ongoing discussion about this DAPLink issue: https://github.com/mbedmicro/DAPLink/issues/115
The behavior that reveal the issue in DAPLink was the following:
1) The device sends a key value pair: `{{key;value}}\n`
2) The host receives the serial data character-by-character.
3) `KiViBufferWalker` matches a key-value pair with the regex `\{\{([\w\d_-]+);([^\}]+)\}\}`, which does not wait for the new the newline of the key-value pair: `{{key;value}}` (note no `\n`).
4) The host immediately sends a new key-value pair to the device. At this time the device is still sending the `\n` character.
5) The device is now receiving a character and attempting to transmit a character at the same time. The particular timing of this case causes a race conditions, which puts …
> Changing the key-value pair regex to include searches for new line

- README.md
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Align how DUT and host together send and receive K-V messages between each other.
* Together with #104 should significantly improve e.g, mbed_drivers::echo tests and DAPLink UX
* While sending (TXD) K-V from `htrun` logger will not print white-space characters new line at the end
* Updated `README` to reflect missing `\n` in K-V format
* Note that `greentea-client` will always send newline character to host, see [here](https://github.com/ARMmbed/greentea-client/blob/master/source/test_env.cpp#L211).
```
mbedgt: test suite report:
+--------------+---------------+-------------------------+--------+--------------------+-------------+
| target       | platform_name | test suite              | result | elapsed_time (sec) | copy_method | …
```
> Add back wrongly removed '\n' K-V pair sent to the device

- mbed_host_tests/host_tests/base_host_test.py
Changes:
* This event is available in `greentea-client v1.3.0`
* `__testcase_name` event passes from `utest` to Greentea information about all test case names available
* Impact:
* mbed-os: [ Provide list of test case names to greentea prior to running test. #1 ](https://github.com/adbridge/mbed-os/pull/1)
* Greentea: [Add support for SKIPPED test cases #158 ](https://github.com/ARMmbed/greentea/pull/158)
* greentea-client: [Add new key "__testcase_name". #15 ](https://github.com/ARMmbed/greentea-client/pull/15)
> Add new event name __testcase_name

- mbed_host_tests/host_tests_event_loop/default_event_loop.py
* Added missing `self` when using `self.result`
* Fixes issue #115
> Fix for Issue #115

- README.md
- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
This commit fixes an intermittent failure with the multiprocess Queue used
within the host test. There is a chance that a Queue will return that it
is empty even if an item has been added to it (see the Queue documentation
here:
https://docs.python.org/2/library/multiprocessing.html#pipes-and-queues).
This issue intermittently arrises in the following scenario:
- A DUT sends the {{end;success}} KV pair
- A DUT sends the {{__exit;0}} KV pair
- The {{end;success}} KV pair is pulled from the queue, which puts a
callback for notify_complete to be called (after the __exit KV pair)
- The {{__exit;0}} KV pair is pulled from the queue, which breaks out of
the loop
- The queue is checked to see if it is empty. This is the intermittent
point of failure, as this sometimes returns True even though …
> Fixing issue with multiprocess Queue

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
- mbed_host_tests/host_tests_toolbox/host_functional.py
* Add command line switch `--baud-rate` to specify the baud rate of the target
* Switch overrides value from target ID, mbed-ls, `-d,--disk-path` disk/mount point, `-p <port>:<baud rate>` for serial port
* This pull request implements part of #87
> Add command line switch to specify baud rate

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Key,Value parsing is reworked to separate key,Value protocol format and need to limit request response based on ```\n```. See #104 for context. Also affects #123 
Additionally the ```self.buff``` was being appended with received strings without being cleared and without being needed as only ```self.buff_idx``` onward string was parsed. Looks like a memory leak.
> KV parsing rework with newline termination in mind

- mbed_host_tests/host_tests_runner/host_test_default.py
In actual code below there is a tight loop:
```
while (time() - start_time) < timeout_duration:
self.logger.prn_inf("Tight loop")
if not event_queue.empty():
try:
(key, value, timestamp) = event_queue.get(timeout=1)
except QueueEmpty:
continue    
```
```self.logger.prn_inf("Tight loop")``` line is added to demonstrate this. Try this and you can observe how much it is printed.
It can have a vicious impact on slower platforms like RPi where starting conn process takes time hence more spinning on checking ```queue.empty()```.
Check ```if not event_queue.empty():``` causes the tight loop as it evaluates to False until there is data in the queue. This check is redundant as check element in the queue inside a ```try``` block and catch ```QueueEmpty``` exception and return to the loop. …
> Fixed tight loop while checking event_queue

- mbed_host_tests/host_tests_runner/host_test_default.py
* Detect when coverage is being output, and switch to an idle timeout, where the timer is reset whenever a new coverage packet is received.
* The idle timeout with timeout when a key value pair hasn't been received within the idle timeout duration, which by default is 10 seconds.
* Idle timeout saves the remaining time in the original timeout, and when a key that is not coverage is received, that timeout is restored.
* This is needed as coverage takes far longer to receive from the target than the timeouts that are set by the test, which causes most of the coverage data to be missed, and most of the tests to fail because of timeouts.
> Add idle timeout for coverage

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Three changes:
- Added a delay in call to ```Serial.read()``` as ```timeout``` is set to 0 making ```read()``` non blocking. This makes connection process loop to keep spinning on ```read()``` when there is no data resulting in high CPU usage. Serial timeout is not used as blocking ```read``` call impacts thread switching in python causing undefined behaviour. 
- Avoiding K,V pair lines/ data from printing as ```printf``` prints (```__rxd_line```) from the target.
- Removed use of ```event_queue.empty()``` from ```process_code_coverage()``` as it causes spinning in the loop when there is not element in queue.
> Fixed performance issue due to spinning on non blocking Serial.read()

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
This PR is a continuation of the work done in #126 
The connection process can sometimes take a lot longer to begin if the system is under heavy load. This allows for a configurable timeout for the connection process to start up, defaulting to 60 seconds. If the connection process fails to start, it returns a result of "TIMEOUT".
Here is what the output looks like if the connection process times out now (NOTE: I set the timeout very low here to force a timeout):
```
$ mbedhtrun --process-start-timeout=0.01 -m K64F -p COM9:9600 -f "BUILD/tests/K64F/GCC_ARM/TESTS/mbedmicro-rtos-mbed/queue/queue.bin" -d J: -C 4 -c shell -t 0240000025354e450025400d47d00046bb91000097969900 -e "TESTS\host_tests"
[1476390997.58][HTST][INF] host test executor ver. 1.1.3
[1476390997.58][HTST][INF] copy image onto …
```
> Removes connection process from initial timeout section

- mbed_host_tests/host_tests_conn_proxy/conn_primitive.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Currently, if the serial port fails to open then htrun still attempts to send the `sync` command. This PR checks the serial port before writing to it. If it is not connected, it fails with a relevant error message. It also allows the connector primitives to use the default implementation for the `error` function since they were identical any way.
```
mbedgt: mbed-host-test-runner: started
[1478124379.62][HTST][INF] host test executor ver. 1.1.4
[1478124379.62][HTST][INF] copy image onto target...
[1478124379.62][COPY][INF] Waiting up to 60 sec for '110100004420312041474339323037313330303997969903' mount point (current is 'D:')...
1 file(s) copied.
[1478124395.29][HTST][INF] starting host test process...
[1478124395.65][CONN][INF] starting connection process...
[1478124395.65][CONN][INF] …
```
> Catching serial port failure quickly

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_plugins/module_reset_mbed.py
On Linux polling serial port via ```mbedls``` does not work. As the port appears quite quickly after reflashing. But isn't ready for opening. Hence it gives error: 
```
[errno 16] Device or resource busy: '/dev/ttyACM0'
``` 
This PR retries opening serial port for ```polling_time``` times (supply by option ```--polling-time```).
Also it is observed that statement ```serial.Serial.break_condition = False``` raises ```[Errno 32] Broken pipe```. But it does not affect further use of ```serial.Serial``` object.
> Polling for serial port to get ready (in linux)

- README.md
- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/module_copy_ublox.py
- mbed_host_tests/host_tests_plugins/module_reset_ublox.py
After merge of `mbed-os` pull request [3011](https://github.com/ARMmbed/mbed-os/pull/3011) , this pull request adds the necessary hook files to use `htrun` tests on the `SARA_NBIOT_EVK` target (since the target does not currently include a magic chip).
> Add Sara-N host test hooks.

- README.md
- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_runner/host_test_default.py
This feature adds option ```--compare-log``` to compare target serial with a templated comparision log. Please see ```README.md``` changes for details.
This is PR is open for discussion and adding more scenarios in consideration.
@adbridge @bridadan Please review.
> Log comparision feature

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_plugins/module_copy_mbed.py
- mbed_host_tests/host_tests_plugins/module_copy_shell.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- mbed_host_tests/host_tests_runner/mbed_base.py
Changes:
- Unify polling timeout use by serial and remote connection primitive
- Fix name from pooling to polling
- Fixes https://github.com/ARMmbed/htrun/issues/136
- Recommended change in greentea to pass the option ```--poll-time``` to htrun
> Unification of poll_ing_timeout used in serial and remote conn primitive

- mbed_host_tests/host_tests_runner/host_test_default.py
This change stops stripping the received lines, making the saved output look closer to the actual output you see in a serial terminal.
It also fixes an issue when comparing an example output where the timeouts are set differently. This is because when the loop enters the "cosume_premable_events" part, it adds an extra 60 seconds to execution time. This was only being done when "serial_output_file" was set, now it's being done when "compare_log" is set as well (by changing the if/else structure).
> Log comparison changes

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
Looks like some references to `self.serial_pooling` were missed in #137. It's currently causing a traceback on master, this should fix it!
> Fixes traceback caused by wrong variable reference

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Somehow '--skip-reset' was being ignored. This PR restores the
functionality. Should fix #142 (original issue located here: https://github.com/ARMmbed/mbed-cli/issues/411)
> Fixes --skip-reset functionality

- mbed_host_tests/host_tests_runner/host_test_default.py
Changes:
- Fixed missing newline at end of every log line while writing to the serial output file.
- Added a descriptive message at the end indicating that log did not match.
> Fix missing newline in written log

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_plugins/__init__.py
- mbed_host_tests/host_tests_plugins/module_copy_pyocd.py
- mbed_host_tests/host_tests_plugins/module_reset_pyocd.py
- mbed_host_tests/host_tests_runner/host_test_default.py
- setup.py
Lines from template log are first matched literally and then as regex. In failure cases a line that is expected to match literally will not match and be tried as a regex patter. If the line has unqualified regex it may raise exception. Hence regex exception should be handled as a possibility and match() function should return False (no match) on exception.
@bridadan @adbridge Please review.
> Handle regex exception when comparing log

- README.md
Code will not compile as it references
```C++
GREENTEA_TSUITE_RESULT(true);
```
@bridadan
> Update reference to GREENTEA_TESTSUITE_RESULT

- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Changes:
- Make test aware of the environment. This helps in mbedtls testing where the host test need to run tests from test vectors file.
- Fix ```notify_complete``` not being able to terminate the test.
@bridadan @adbridge Please review. Needed by mbedtls on target testing.
> Make execution environment available to the test

- mbed_host_tests/host_tests_conn_proxy/conn_primitive.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
Writing to a Serial port works differently on Linux than on Windows. The
pySerial documentation says that the `serial.write()` function will default
to blocking if `write_timeout` is not set. On Linux, this means that the
`serial.write()` blocks forever if the device has not received the data (which
happens in certain cases for different boards). This also occurs in
Windows, however it appears that Windows has a relatively large internal
buffer (~10K) that will cause the serial.write() function to return
immediately if there is still space in the buffer. Only when you send
large amounts of data does the function block.
This PR attempts to standardize the behavior of the host test (and to
prevent indefinite hangs) by introducing a default write timeout of 5
seconds.
It also adds checks …
> Serial write timeout

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
If remote connection fails do not clear selected resource because it's still allocated
Fix for #153
> do not clear selected resource when connect fails

- mbed_host_tests/host_tests_plugins/module_copy_shell.py
It destroys performance.
Instead, sync just the file system that contains the file we care about
> Don't sync everything

- mbed_host_tests/host_tests_runner/host_test_default.py
Currently connection sub-process is started and ```htrun``` waits for ```process_start_timeout``` secs. This is not correct when global resource manager is used. As resource allocation can take really long time.
@bridadan @studavekar Please review. Required for use with RAAS.
> Wait forever in case global resource manager

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
this is required as when force flash is not enabled, If device is not flashed
probably because of out-of-order copy or any other reason. if its reported
as flashed properly because FAIL.TXT or ASSERT.txt is not created we may see
next test failure.
> force flash the device when using RaaS

- mbed_host_tests/__init__.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Currently this argument was used but never set, always defaulting to 1 sec. In
case of RaaS and when device boot takes longer we end up of sending multiple
sync_packet causing few test to fail like echo test.
> add args --sync-timeout parameter delay between __sync packets

- mbed_host_tests/host_tests/base_host_test.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- mbed_host_tests/host_tests_conn_proxy/conn_primitive_serial.py
- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
- mbed_host_tests/host_tests_runner/host_test_default.py
Add a host test reset function to allow the current DUT to be reset. This allow unexpected power loss to be tested.
CC @bridadan @studavekar @theotherjimmy
> Allow a host test to reset the device under test

- mbed_host_tests/host_tests_plugins/module_copy_mps2.py
The run_command function is called with too many parameters. Fixes #175.
> Fix a copy error on Linux

- mbed_host_tests/host_tests_plugins/module_copy_mps2.py
- test/mps2_copy.py
To allow to write .elf file path in the test_spec.json file, this patch
keeps the same extension when copying mbed.extension file onto the MPS2
board.
Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>
> Keep the same extension of the executable files copied to MPS2

- mbed_host_tests/host_tests_plugins/host_test_plugins.py
- mbed_host_tests/host_tests_runner/mbed_base.py
Replace all calls to `list_mbeds_by_targetid()` since it has been deprecated in mbed-ls. This should fix ARMmbed/mbed-ls#267
> Remove calls to deprecated list_mbeds_ext functions

- mbed_host_tests/host_tests_plugins/module_reset_mps2.py
- test/mps2_reset.py
This patch adds a sync command to ensure that the reboot.txt file has
really been copied into the device to be sure that the reboot process
has started. Fixes #179.
Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>
@malcolm-brooks-arm
> Ensure the reboot step happens on MPS2

- mbed_host_tests/__init__.py
The default value was picked from https://github.com/ARMmbed/greentea/blob/747460ccd80917264fbef79ae13ff9834d014450/mbed_greentea/mbed_target_info.py#L46
> set default value for --program_cycle_s

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py
- test/conn_primitive_remote.py
**IN PROGRESS**
Relates to MBEDOSTEST-37
* remove obsolete API usages and use new one
* fixes bug from read in case of reading fails
* fixes finish to releasing resource in case of close_connection fails
* fix connected function
* connected() validates that resource is also allocated
* validates that write() success
* release resource if flash or connection fails
* catch generic Exception when allocate fails
* validates that resource is allocated and connected before writing/reading it
* validates that resource is allocated before releasing
* improve traces
* pylint cleaning
* add basic tests
> Several improvements for Global Resource Manager connection

- mbed_host_tests/__init__.py
This should fix https://github.com/ARMmbed/greentea/issues/274#issuecomment-395660594.
Could you take a quick look @jamesbeyond?
> Fixing incorrect inclusion of fastmodel as default connproxy

- mbed_host_tests/__init__.py
MBEDOSTEST-90
**master:**
```
$ mbedhtrun
[1530001200.88][root]Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[1530001200.91][root]Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[1530001200.92][HTST][INF] host test executor ver. 1.3.1
[1530001200.92][HTST][INF] copy image onto target...
Traceback (most recent call last):
File "/usr/local/bin/mbedhtrun", line 9, in <module>
load_entry_point('mbed-host-tests==1.3.1', 'console_scripts', 'mbedhtrun')()
File "build/bdist.linux-x86_64/egg/mbed_host_tests/mbedhtrun.py", line 34, in main
File "build/bdist.linux-x86_64/egg/mbed_host_tests/host_tests_runner/host_test_default.py", line 524, in execute
File "build/bdist.linux-x86_64/egg/mbed_host_tests/host_tests_runner/mbed_base.py", line 179, in …
```
> fix 'mbedhtrun crashes when no parameters given'

- mbed_host_tests/host_tests_runner/mbed_base.py
MBEDOSTEST-91
**master(fail):**
```
$ mbedhtrun -d /media/alekla01/DAPLINK -p /dev/ttyACM0 -f "test.bin" -C 4 -c shell -m K64F
[1530018523.87][root]Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[1530018523.89][root]Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[1530018523.91][HTST][INF] host test executor ver. 1.3.1
[1530018523.91][HTST][INF] copy image onto target...
cp: cannot stat 'test.bin': No such file or directory
[1530018523.92][COPY][ERR] [ret=1] Command: ['cp', 'test.bin', '/media/alekla01/DAPLINK/test.bin']
cp: cannot stat 'test.bin': No such file or directory
[1530018527.93][COPY][ERR] [ret=1] Command: ['cp', 'test.bin', '/media/alekla01/DAPLINK/test.bin']
...
```
**modified(fail):**
```
$ mbedhtrun -d …
```
> Fix 'mbedhtrun tries to flash non existing file multiple times'

- mbed_host_tests/host_tests_conn_proxy/conn_proxy.py
To solve issue: https://github.com/ARMmbed/htrun/issues/193
Solution: 
The host would send an initial sync, and if it receives a bad sync it will reset the part and wait until a certain duration  before sending the second sync packet. Meanwhile, if it receives another sync packet from DUT (if the buffer was not empty), it will reset the part again. 
Corner case: The DUT has 4 bad syncs in its buffer, and when it sent out the 3rd one, host received it and told it to reset, and then host itself reached a stage where it is ready to send second sync. At this point, device sends out the 4th sync and begins executing the tests (since there is no ack from host), and this test is one of those kind where it would continuously spew out data to host via the buffer, in this case, sending second sync …
> Reset device after bad sync

- README.md
In some cases where we're testing complex applications, need to more time to get the expected output.
This documentation change helps the user to override the timeout setting.
Resolves https://github.com/ARMmbed/htrun/issues/211
> Document polling-timeout setting for testing apps

- mbed_host_tests/host_tests_conn_proxy/conn_primitive_fastmodel.py
**add delicate `reset()` function for fast models**
the `reset()` and `run()` were considered to be the same, but in some cases they are different
**change the create to setup function to match fm_agent 1.1**
fm_agent been updated to version 1.1, slight chnages about how to `create()` or `setup()` a model. This PR just to match with the new changes. Also fm_agent module are backwards compatible
> Update htrun fastmodel connector to match with newer fm_agent 

- mbed_host_tests/host_tests_runner/host_test_default.py
This minimalistic PR adds support to dynamically sett/adjust a test timeout via DUT messages `{{__timeout_set,int}}`, `{{__timeout_adjust,int}}`.
The is particularly useful when a device is making a download (say firmware update), where the speed might dynamically change based on various conditions. With this feature, the DUT might notify the host that it's alive and running, just slower than expected.
A typical usecase would be a unified IP connectivity test, where the time to complete over Ethernet and Wifi would be significantly faster than 2G/3G, let alone NBIoT/CAT-M1.
As discussed with @bridadan
> Feature: dynamic timeouts

- mbed_host_tests/host_tests_plugins/module_copy_pyocd.py
Corrected the reference to `board.getTargetType()` in the pyocd copy plugin to the new property name `session.board.target_type`.
Tested by using `mbedhtrun` to flash a binary to a FRDM-K64F.
> Fix old name reference in pyocd copy plugin
